### ISSUE TITLE
Segmentation Fault while parsing a map where a string is expected

### ISSUE THREAD

**Issue by slaperche-scality** [tlsa/libcyaml#108]
It seems that the parser crash when the reality doesn't match the schema (for instance, if one field is defined as a string in the schema but the file contains a map).

## How to reproduce

Parsing the following file (`bug.yaml`):

```yaml
global:
  path: {{ .DbnamePath | default "/tmp/index" }}
```

With the following code:

```c
#include <stdio.h>
#include <stdlib.h>

#include <cyaml/cyaml.h>

struct section {
    const char* path;
};

static const cyaml_schema_field_t section_fields_schema[] = {
    CYAML_FIELD_STRING_PTR(
            "path", CYAML_FLAG_POINTER,
            struct section, path, 0, CYAML_UNLIMITED),
    CYAML_FIELD_END
};

struct conf {
    struct section* global;
};

static const cyaml_schema_field_t conf_fields_schema[] = {
    CYAML_FIELD_MAPPING_PTR(
            "global", CYAML_FLAG_POINTER,
            struct conf, global, section_fields_schema),
    CYAML_FIELD_END
};

static const cyaml_schema_value_t conf_schema = {
    CYAML_VALUE_MAPPING(CYAML_FLAG_POINTER, struct conf, conf_fields_schema),
};


static cyaml_config_t cyaml_cfg = {
    .log_level = CYAML_LOG_DEBUG,
    .log_fn = cyaml_log,
    .mem_fn = cyaml_mem,
};


int main(void)
{
    struct conf config;

    cyaml_err_t err = cyaml_load_file(
            "bug.yaml", &cyaml_cfg, &conf_schema, (void **) &config, NULL
    );

    if (err != CYAML_OK) {
        fprintf(stderr, "Error: %s", cyaml_strerror(err));
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
```

Produces:

```
% ./bug
libcyaml:   DEBUG: Load: PUSH[0]: start
libcyaml:   DEBUG: Load: Event: STREAM_START
libcyaml:   DEBUG: Load: Handle state start
libcyaml:   DEBUG: Load: PUSH[1]: in stream
libcyaml:   DEBUG: Load: Event: DOC_START
libcyaml:   DEBUG: Load: Handle state in stream
libcyaml:   DEBUG: Load: PUSH[2]: in doc
libcyaml:   DEBUG: Load: Event: MAPPING_START
libcyaml:   DEBUG: Load: Handle state in doc
libcyaml:   DEBUG: Load: Reading value of type 'MAPPING' (pointer)
libcyaml:   DEBUG: Load: Allocation: 0x555a306e7460 (0 + 8 bytes)
libcyaml:   DEBUG: Load: PUSH[3]: in mapping (key)
libcyaml:   DEBUG: Load: Event: SCALAR
libcyaml:   DEBUG: Load: Handle state in mapping (key)
libcyaml:    INFO: Load: [global]
libcyaml:   DEBUG: Load: Event: MAPPING_START
libcyaml:   DEBUG: Load: Handle state in mapping (value)
libcyaml:   DEBUG: Load: Reading value of type 'MAPPING' (pointer)
libcyaml:   DEBUG: Load: Allocation: 0x555a306e74e0 (0 + 8 bytes)
libcyaml:   DEBUG: Load: PUSH[4]: in mapping (key)
libcyaml:   DEBUG: Load: Event: SCALAR
libcyaml:   DEBUG: Load: Handle state in mapping (key)
libcyaml:    INFO: Load: [path]
libcyaml:   DEBUG: Load: Event: MAPPING_START
libcyaml:   DEBUG: Load: Handle state in mapping (value)
libcyaml:   DEBUG: Load: Reading value of type 'STRING' (pointer)
zsh: segmentation fault (core dumped)  ./bug
```

## Backtrace

```
#0  0x00007fa7c5e9a6f5 in __strlen_avx2 () from /usr/lib/libc.so.6
#1  0x000056026beb115e in cyaml__data_handle_pointer (ctx=0x7ffde18b62b0, schema=0x56026beb87d8 <section_fields_schema+24>, event=0x7ffde18b62c0, value_data_io=0x7ffde18b6198) at src/load.c:1078
#2  0x000056026beb245e in cyaml__read_value (ctx=0x7ffde18b62b0, schema=0x56026beb87d8 <section_fields_schema+24>, data=0x56026d6644e0 "", event=0x7ffde18b62c0) at src/load.c:1892
#3  0x000056026beb294f in cyaml__map_value (ctx=0x7ffde18b62b0, event=0x7ffde18b62c0) at src/load.c:2129
#4  0x000056026beb2d5a in cyaml__load_event (ctx=0x7ffde18b62b0, event=0x7ffde18b62c0) at src/load.c:2317
#5  0x000056026beb2ea8 in cyaml__load (config=0x56026beb9100 <cyaml_cfg>, schema=0x56026beb88c0 <conf_schema>, data_out=0x7ffde18b6600, seq_count_out=0x0, parser=0x7ffde18b63f0) at src/load.c:2373
#6  0x000056026beb30aa in cyaml_load_file (path=0x56026beb5010 "bug.yaml", config=0x56026beb9100 <cyaml_cfg>, schema=0x56026beb88c0 <conf_schema>, data_out=0x7ffde18b6600, seq_count_out=0x0) at src/load.c:2429
#7  0x000056026beaf2d7 in main () at bug.c:44
```

## My guess

Problems seems to come from `cyaml__read_value`:

```c
            if (!cyaml__is_sequence(schema)) {
                    /* Since sequences extend their allocation for each entry,
                     * they're handled in the sequence-specific code.
                     */
                    err = cyaml__data_handle_pointer(ctx, schema, event, &data);
                    if (err != CYAML_OK) {
                            return err;
                    }
            }
```

The condition here only relies on the schema (with `cyaml__is_sequence`, here  `schema.type` is `CYAML_STRING`) regardless of what's really happening (content of `cyaml_event` is `CYAML_EVT_MAP_START`) and :boom: .

**Comment by tlsa** [comment]
Thank you for the excellent test case!  :smile_cat:

Yeah, this is a bug; `cyaml__data_handle_pointer()` was using the event data assuming that it was of a sensible type for string type in the schema, before that check was actually performed later in `cyaml__read_value`.

It should be fixed now.  (See https://github.com/tlsa/libcyaml/pull/109.)

Your test case now detects the malformed input correctly:

```
libcyaml:   DEBUG: Load: PUSH[0]: start
libcyaml:   DEBUG: Load: Event: STREAM_START
libcyaml:   DEBUG: Load: Handle state start
libcyaml:   DEBUG: Load: PUSH[1]: in stream
libcyaml:   DEBUG: Load: Event: DOC_START
libcyaml:   DEBUG: Load: Handle state in stream
libcyaml:   DEBUG: Load: PUSH[2]: in doc
libcyaml:   DEBUG: Load: Event: MAPPING_START
libcyaml:   DEBUG: Load: Handle state in doc
libcyaml:   DEBUG: Load: Reading value of type 'MAPPING' (pointer)
libcyaml:   DEBUG: Load: Allocation: 0x4c93640 (0 + 8 bytes)
libcyaml:   DEBUG: Load: PUSH[3]: in mapping (key)
libcyaml:   DEBUG: Load: Event: SCALAR
libcyaml:   DEBUG: Load: Handle state in mapping (key)
libcyaml:    INFO: Load: [global]
libcyaml:   DEBUG: Load: Event: MAPPING_START
libcyaml:   DEBUG: Load: Handle state in mapping (value)
libcyaml:   DEBUG: Load: Reading value of type 'MAPPING' (pointer)
libcyaml:   DEBUG: Load: Allocation: 0x4c93820 (0 + 8 bytes)
libcyaml:   DEBUG: Load: PUSH[4]: in mapping (key)
libcyaml:   DEBUG: Load: Event: SCALAR
libcyaml:   DEBUG: Load: Handle state in mapping (key)
libcyaml:    INFO: Load: [path]
libcyaml:   DEBUG: Load: Event: MAPPING_START
libcyaml:   DEBUG: Load: Handle state in mapping (value)
libcyaml:   DEBUG: Load: Reading value of type 'STRING' (pointer)
libcyaml:   ERROR: Load: Expecting STRING, got event: MAPPING_START
libcyaml:   DEBUG: Free: Top level data: 0x4c93640
libcyaml:   DEBUG: Free: Freeing key: global (at offset: 0)
libcyaml:   DEBUG: Free: Freeing key: path (at offset: 0)
libcyaml:   DEBUG: Free: Freeing: 0x4c93820
libcyaml:   DEBUG: Free: Freeing: 0x4c93640
libcyaml:   ERROR: Load: Backtrace:
libcyaml:   ERROR:   in mapping field: path
libcyaml:   ERROR:   in mapping field: global
libcyaml:   DEBUG: Load: POP[4]: in mapping (key)
libcyaml:   DEBUG: Load: POP[3]: in mapping (key)
libcyaml:   DEBUG: Load: POP[2]: in doc
libcyaml:   DEBUG: Load: POP[1]: in stream
libcyaml:   DEBUG: Load: POP[0]: start
Error: Invalid value
```
If you do want that value to be treated as a string, use:

```yaml
global:
  path: '{{ .DbnamePath | default "/tmp/index" }}'
```

**Comment by slaperche-scality** [comment]
Ho great! I confirm that this fix my issue :tada: 

Do you plan to do a new release (a v0.1.1 maybe) at some point? (Then I could bump the version of libcyaml I'm depending on).

Thank you for the super quick resolution (and for the explanations) :slightly_smiling_face:
